---
platform:
  domain:
    platform.sj.com
  site:
    shop: ${sjes.domain}/shop/

server:
  port: 20001
  session:
    timeout: 43200
spring:

  thymeleaf:
    check-template-location: true
    prefix: classPath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  resources:
    static-locations:
#      - file:///F:/Develop/baiduNew/sjes-baidu-admin/src/main/resources/templates/
      - classPath:/templates/
  data:
    mongodb:
      host: srv3.sanjiang.info
      port: 27017
      database: sj-baidu-admin

  profiles: production
  datasource:
    url: jdbc:oracle:thin:@193.0.10.53:1521:sjos
    username: sjhub
    password: sjhubdb
#    url: jdbc:oracle:thin:@193.0.10.224:1521:sjostest
#    username: sjhub
#    password: sjhub
    driverClassName: oracle.jdbc.OracleDriver
    max-active: 50
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 5
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
  jpa:
    show_sql: true
    hibernate:
      show_sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
  # 设置redis服务
  redis:
    database: 3
#    host: srv3.sanjiang.info
    host: prod2.sjes.sanjiang.info
    prod2: b2c.prod2.sanjiang.info
    pool:
      max-active: 8
      min-idle: 2
      max-wait: -1
      max-idle: 10
log4j:
  logger:
    org:
      hibernate:
        SQL: trace
        type: trace
security:
  ignored:
    - /favicon.ico
    - /images/**
    - /styles/**
    - /scripts/**
  user:
    name: admin
    password: admin

#分类表数据库
dwh:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@193.0.10.45:1521:sjom
    username: dwh
    password: sjos
    poolSize: 100
    max-active: 20
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 5
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
#中间库
sjjk:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@193.0.0.5:1521:sjjk
    username: sj
    password: sjjk
    poolSize: 100
    max-active: 50
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 40
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL

default:
  bddj: 10001
  jddj: 10002
  tbdj: 10003
  sjgw: 10004
  page: 0
  pageSize: 10
#  port: http://193.0.10.121:25000
#正式
  sjHubPort:  http://193.0.10.121:25000
  sjHubPort2: http://193.0.10.175:25000
#  sjHubPort:  http://localhost:25000
  jdServerPort: http://193.0.10.50 #正式
#  jdServerPort: http://193.0.1.248:5152
#baidu:
#  #私钥
#  secret: 7e311c6c88165a63
#  #api版本号
#  version: 2
#  #三江对应的百度外卖账户
#  source: 65293
#  #请求url
#  apiUrl: http://api.waimai.baidu.com
#  request:
#    orderCancel: order.cancel
#    orderDetail: order.get
#    orderConfirm: order.confirm
#    orderStatus: order.status.get
mongeez:
  enabled: true
  location: db/dev/mongeez.xml

logging:
  level:
    org.mongodb.driver.protocol: debug
    org.mongeez: debug
file:
#  path: src/main/resources/templates/excel
#  path: /home/sanjiang/sjes/sj-baidu-admin/src/main/resources/templates/excel
#prod2
  path: /home/sjes/sj-hub/sj-baidu-admin/src/main/resources/templates/excel
---
eureka:
  instance:
    hostname: localhost1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
platform:
  domain:
    platform.sj.com
  site:
    shop: ${sjes.domain}/shop/
server:
  port: 20001
  session:
    timeout: 43200
spring:
  thymeleaf:
    check-template-location: true
    prefix: classPath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  resources:
    static-locations:
#      - file:///F:/Develop/baiduNew/sjes-baidu-admin/src/main/resources/templates/
      - classPath:/templates/
  data:
    mongodb:
      host: srv3.sanjiang.info
      port: 27017
      database: sj-baidu-admin
  profiles: local2
  datasource:
#    url: jdbc:oracle:thin:@193.0.10.53:1521:sjos
#    username: sjhub
#    password: sjhubdb
    url: jdbc:oracle:thin:@193.0.10.224:1521:sjostest
    username: sjhub
    password: sjhub
    driverClassName: oracle.jdbc.OracleDriver
    max-active: 50
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 5
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
  jpa:
    show_sql: true
    hibernate:
      show_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false
  # 设置redis服务
  redis:
    database: 4
    host: srv3.sanjiang.info
    prod2: srv3.sanjiang.info
#    host: srv3.sanjiang.info
#    host: prod2.sjes.sanjiang.info
    pool:
      max-active: 8
      min-idle: 2
      max-wait: -1
      max-idle: 10
log4j:
  logger:
    org:
      hibernate:
        SQL: trace
        type: trace
security:
  ignored:
    - /favicon.ico
    - /images/**
    - /styles/**
    - /scripts/**
  user:
    name: admin
    password: admin
#分类表数据库
dwh:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@193.0.10.45:1521:sjom
    username: dwh
    password: sjos
    poolSize: 100
    max-active: 20
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 5
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
#中间库
sjjk:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@193.0.0.5:1521:sjjk
    username: sj
    password: sjjk
    poolSize: 100
    max-active: 50
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 40
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL

default:
  bddj: 10001
  jddj: 10002
  tbdj: 10003
  sjgw: 10004
  page: 0
  pageSize: 10
#  port: http://193.0.10.121:25000
#正式
#  sjHubPort:  http://193.0.10.121:25000
#  sjHubPort2: http://193.0.10.175:25000
  sjHubPort:  http://localhost:24000
  sjHubPort2: http://localhost:24000
#  jdServerPort: http://193.0.10.50 #正式
#  jdServerPort: http://193.0.1.248:5152
  jdServerPort: http://localhost:5152
#baidu:
#  #私钥
#  secret: 7e311c6c88165a63
#  #api版本号
#  version: 2
#  #三江对应的百度外卖账户
#  source: 65293
#  #请求url
#  apiUrl: http://api.waimai.baidu.com
#  request:
#    orderCancel: order.cancel
#    orderDetail: order.get
#    orderConfirm: order.confirm
#    orderStatus: order.status.get
mongeez:
  enabled: true
  location: db/dev/mongeez.xml
logging:
  level:
    org.mongodb.driver.protocol: debug
    org.mongeez: debug
file:
  path: src/main/resources/templates/excel
#  path: /home/sanjiang/sjes/sj-baidu-admin/src/main/resources/templates/excel
#prod2
#  path: /home/sjes/sj-hub/sj-baidu-admin/src/main/resources/templates/excel

---
platform:
  domain:
    platform.sj.com
  site:
    shop: ${sjes.domain}/shop/
server:
  port: 20002
  session:
    timeout: 43200
spring:
  thymeleaf:
    check-template-location: true
    prefix: classPath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  resources:
    static-locations:
#      - file:///F:/Develop/baiduNew/sjes-baidu-admin/src/main/resources/templates/
      - classPath:/templates/
  data:
    mongodb:
      host: srv3.sanjiang.info
      port: 27017
      database: sj-baidu-admin
  profiles: srv5
  datasource:
#    url: jdbc:oracle:thin:@193.0.10.53:1521:sjos
#    username: sjhub
#    password: sjhubdb
    url: jdbc:oracle:thin:@193.0.10.224:1521:sjostest
    username: sjhub
    password: sjhub
    driverClassName: oracle.jdbc.OracleDriver
    max-active: 50
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 5
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
  jpa:
    show_sql: true
    hibernate:
      show_sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
  # 设置redis服务
  redis:
    database: 4
    host: srv3.sanjiang.info
    prod2: srv3.sanjiang.info
#    host: srv3.sanjiang.info
#    host: prod2.sjes.sanjiang.info
    pool:
      max-active: 8
      min-idle: 2
      max-wait: -1
      max-idle: 10
log4j:
  logger:
    org:
      hibernate:
        SQL: trace
        type: trace
security:
  ignored:
    - /favicon.ico
    - /images/**
    - /styles/**
    - /scripts/**
  user:
    name: admin
    password: admin
#分类表数据库
dwh:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@193.0.10.45:1521:sjom
    username: dwh
    password: sjos
    poolSize: 100
    max-active: 20
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 5
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
default:
  bddj: 10001
  jddj: 10002
  tbdj: 10003
  sjgw: 10004
  page: 0
  pageSize: 10
#  port: http://193.0.10.121:25000
#正式
#  sjHubPort:  http://193.0.10.121:25000
#  sjHubPort2: http://193.0.10.175:25000
  sjHubPort:  http://localhost:24000
  sjHubPort2: http://localhost:24000
#  jdServerPort: http://193.0.10.50 #正式
#  jdServerPort: http://193.0.1.248:5152
  jdServerPort: http://localhost:5152
#baidu:
#  #私钥
#  secret: 7e311c6c88165a63
#  #api版本号
#  version: 2
#  #三江对应的百度外卖账户
#  source: 65293
#  #请求url
#  apiUrl: http://api.waimai.baidu.com
#  request:
#    orderCancel: order.cancel
#    orderDetail: order.get
#    orderConfirm: order.confirm
#    orderStatus: order.status.get
mongeez:
  enabled: true
  location: db/dev/mongeez.xml
logging:
  level:
    org.mongodb.driver.protocol: debug
    org.mongeez: debug
file:
  path: /home/user/sj-hub/sj-baidu-admin/src/main/resources/templates/excel

